spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-jpa-demo
    username: root
    password: 11111111
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    ### 运行时输出SQL语句
    show-sql: true